### ISSUE TITLE
Regresión polinomial

### ISSUE THREAD

**Issue by lucianoamor** [lucianoamor/la-borra#10]
Permitir cambiar grado

**Comment by andytow** [comment]
Que las lineas solo aparezcan cuando se hace mouseover en la tabla de la izquierda, aparecen todas cuando mouseover, con resaltada la del candidato, cuando mouseout de la tabla quedan solo los circulos. Ver que hacer con el checkbox de lineas y puntos, unificarlos

**Comment by andytow** [comment]
El control del grado de polinomio puede ir en el espacio en blanco arriba de candidatos, asi cuando se actualiza es mouseover directo sobre la tabla
